version: "3"

services: 
  dbsrv: 
    environment: 
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_USER: wordpress
    image: "mysql:5.7"
    restart: always
    volumes: 
      - "dbdata:/var/lib/mysql"
    networks: 
      - website_net

  websrv: 
    deploy: 
      replicas: 2
    image: ckc3690/websrv:latest
    ports: 
      - "8100:80"
    networks: 
      - website_net
 
    
  wordpress: 
    depends_on: 
      - dbsrv
    environment: 
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
    image: "wordpress:latest"
    ports: 
      - "8200:443"
    restart: always
    networks: 
      - website_net

volumes:
  dbdata:

networks:
  website_net:

