swarm-managers: [
    swarm-manager-1,
    swarm-manager-2
]
swarm-vpc-id: vpc-2e1f3957
swarm-workers: [
    swarm-worker-1,
    swarm-worker-2
]
swarm_manager_1_private_ip: 10.100.139.148
swarm_manager_1_public_ip: 54.187.225.120
