swarm-managers: [
    swarm-manager-1,
    swarm-manager-2
]
swarm-vpc-id: vpc-60e2a21b
swarm-workers: [
    swarm-worker-1,
    swarm-worker-2
]
swarm_manager_1_private_ip: 10.100.136.65
swarm_manager_1_public_ip: 54.236.76.162
